version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: perfin
      POSTGRES_USER: perfin
      POSTGRES_PASSWORD: perfin
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db: