# Generated by Django 4.1.5 on 2023-01-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='category',
            field=models.CharField(choices=[('study', 'Учеба'), ('food', 'Еда'), ('credit', 'Кредиты'), ('other', 'Другое')], default='other', max_length=15, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(choices=[('study', 'Учеба'), ('food', 'Еда'), ('credit', 'Кредиты'), ('other', 'Другое')], default='other', max_length=15, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
