# Generated by Django 4.1.5 on 2023-01-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_reminder_category_alter_spending_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='category',
            field=models.CharField(choices=[('study', 'Учеба'), ('food', 'Еда'), ('credit', 'Кредиты'), ('health', 'Здоровье'), ('purchase', 'Покупки'), ('other', 'Другое')], default='other', max_length=15, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(choices=[('study', 'Учеба'), ('food', 'Еда'), ('credit', 'Кредиты'), ('health', 'Здоровье'), ('purchase', 'Покупки'), ('other', 'Другое')], default='other', max_length=15, verbose_name='Категория'),
        ),
    ]
