# Generated by Django 4.1.5 on 2023-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_reminder_amount_alter_reminder_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(null=True),
        ),
    ]
